package com.wakandaspace.drools_price_model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AssumptionsUsedUtil implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public AssumptionsUsedUtil() {
    }




}