package com.wakandaspace.drools_price_model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Benefit implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("benefitType")
	private java.lang.String benefitType;
	@org.kie.api.definition.type.Label("covered")
	private java.lang.Boolean covered;
	@org.kie.api.definition.type.Label("wardType")
	private java.lang.String wardType;
	@org.kie.api.definition.type.Label("numberOfSessions")
	private int numberOfSessions;
	@org.kie.api.definition.type.Label("itemCoverage")
	private java.lang.String itemCover;

	public Benefit() {
	}

	public java.lang.String getBenefitType() {
		return this.benefitType;
	}

	public void setBenefitType(java.lang.String benefitType) {
		this.benefitType = benefitType;
	}

	public java.lang.Boolean getCovered() {
		return this.covered;
	}

	public void setCovered(java.lang.Boolean covered) {
		this.covered = covered;
	}

	public java.lang.String getWardType() {
		return this.wardType;
	}

	public void setWardType(java.lang.String wardType) {
		this.wardType = wardType;
	}

	public int getNumberOfSessions() {
		return this.numberOfSessions;
	}

	public void setNumberOfSessions(int numberOfSessions) {
		this.numberOfSessions = numberOfSessions;
	}

	public java.lang.String getItemCover() {
		return this.itemCover;
	}

	public void setItemCover(java.lang.String itemCover) {
		this.itemCover = itemCover;
	}

	public Benefit(java.lang.String benefitType, java.lang.Boolean covered,
			java.lang.String wardType, int numberOfSessions,
			java.lang.String itemCover) {
		this.benefitType = benefitType;
		this.covered = covered;
		this.wardType = wardType;
		this.numberOfSessions = numberOfSessions;
		this.itemCover = itemCover;
	}

}