package com.wakandaspace.drools_price_model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BenefitGroup implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label("coverageFrom")
	private java.lang.String coverageFrom;

	@org.kie.api.definition.type.Label("limit")
	private double limit;

	@org.kie.api.definition.type.Label("coveredDays")
	private double coveredDays;

	@org.kie.api.definition.type.Label("numberOfSession")
	@org.kie.api.definition.type.Description("none=0\nunlimited=-1\nelse amount")
	private double numberOfSession;
	public BenefitGroup() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getCoverageFrom() {
		return this.coverageFrom;
	}

	public void setCoverageFrom(java.lang.String coverageFrom) {
		this.coverageFrom = coverageFrom;
	}

	public double getLimit() {
		return this.limit;
	}

	public void setLimit(double limit) {
		this.limit = limit;
	}

	public double getCoveredDays() {
		return this.coveredDays;
	}

	public void setCoveredDays(double coveredDays) {
		this.coveredDays = coveredDays;
	}

	public double getNumberOfSession() {
		return this.numberOfSession;
	}

	public void setNumberOfSession(double numberOfSession) {
		this.numberOfSession = numberOfSession;
	}

	public BenefitGroup(java.lang.String name, java.lang.String coverageFrom,
			double limit, double coveredDays, double numberOfSession) {
		this.name = name;
		this.coverageFrom = coverageFrom;
		this.limit = limit;
		this.coveredDays = coveredDays;
		this.numberOfSession = numberOfSession;
	}

}