package com.wakandaspace.drools_price_model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BenefitCategory implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("coverageFrom")
	private java.lang.String coverageFrom;
	@org.kie.api.definition.type.Label("limit")
	@org.kie.api.definition.type.Description("unlimited->1\nnone->0")
	private java.lang.Double limit;

	@org.kie.api.definition.type.Label(value = "benefitsList")
	private java.util.List<com.wakandaspace.drools_price_model.Benefit> benefitsList;

	public BenefitCategory() {
	}

	public java.lang.String getCoverageFrom() {
		return this.coverageFrom;
	}

	public void setCoverageFrom(java.lang.String coverageFrom) {
		this.coverageFrom = coverageFrom;
	}

	public java.lang.Double getLimit() {
		return this.limit;
	}

	public void setLimit(java.lang.Double limit) {
		this.limit = limit;
	}

	public BenefitCategory(
			java.lang.String coverageFrom,
			java.lang.Double limit,
			java.util.List<com.wakandaspace.drools_price_model.Benefit> listeBenefits) {
		this.coverageFrom = coverageFrom;
		this.limit = limit;
		this.listeBenefits = listeBenefits;
	}

	public java.util.List<com.wakandaspace.drools_price_model.Benefit> getBenefitsList() {
		return this.benefitsList;
	}

	public void setBenefitsList(
			java.util.List<com.wakandaspace.drools_price_model.Benefit> benefitsList) {
		this.benefitsList = benefitsList;
	}

	public BenefitCategory(
			java.lang.String coverageFrom,
			java.lang.Double limit,
			java.util.List<com.wakandaspace.drools_price_model.Benefit> benefitsList) {
		this.coverageFrom = coverageFrom;
		this.limit = limit;
		this.benefitsList = benefitsList;
	}

}