package com.wakandaspace.drools_price_model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Benefit implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("benefitType")
	private java.lang.String benefitType;
	@org.kie.api.definition.type.Label("covered")
	private java.lang.Boolean covered;
	@org.kie.api.definition.type.Description(value = "Number of sessions, consultations, Days, Hours...")
	@org.kie.api.definition.type.Label(value = "item")
	private java.lang.String item;

	@org.kie.api.definition.type.Label(value = "wardType")
	private java.lang.String wardType;

	@org.kie.api.definition.type.Label(value = "coverageDays")
	private int coverageDays;
	public Benefit() {
	}

	public java.lang.String getBenefitType() {
		return this.benefitType;
	}

	public void setBenefitType(java.lang.String benefitType) {
		this.benefitType = benefitType;
	}

	public java.lang.Boolean getCovered() {
		return this.covered;
	}

	public void setCovered(java.lang.Boolean covered) {
		this.covered = covered;
	}

	public java.lang.String getItem() {
		return this.item;
	}

	public void setItem(java.lang.String item) {
		this.item = item;
	}

	public java.lang.String getWardType() {
		return this.wardType;
	}

	public void setWardType(java.lang.String wardType) {
		this.wardType = wardType;
	}

	public int getCoverageDays() {
		return this.coverageDays;
	}

	public void setCoverageDays(int coverageDays) {
		this.coverageDays = coverageDays;
	}

	public Benefit(java.lang.String benefitType, java.lang.Boolean covered,
			java.lang.String item, java.lang.String wardType, int coverageDays) {
		this.benefitType = benefitType;
		this.covered = covered;
		this.item = item;
		this.wardType = wardType;
		this.coverageDays = coverageDays;
	}

}