package com.wakandaspace.drools_price_model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BenefitCategory implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "coverageFrom")
	private java.lang.String coverageFrom;
	@org.kie.api.definition.type.Description(value = "unlimited->1\nnone->0")
	@org.kie.api.definition.type.Label(value = "limit")
	private java.lang.Double limit;

	public BenefitCategory() {
	}

	public java.lang.String getCoverageFrom() {
		return this.coverageFrom;
	}

	public void setCoverageFrom(java.lang.String coverageFrom) {
		this.coverageFrom = coverageFrom;
	}

	public java.lang.Double getLimit() {
		return this.limit;
	}

	public void setLimit(java.lang.Double limit) {
		this.limit = limit;
	}

	public BenefitCategory(java.lang.String coverageFrom, java.lang.Double limit) {
		this.coverageFrom = coverageFrom;
		this.limit = limit;
	}

}