package com.wakandaspace.drools_price_model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Expense implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("lossRatioTarget")
	private double lossRatioTarget;

	public Expense() {
	}

	public double getLossRatioTarget() {
		return this.lossRatioTarget;
	}

	public void setLossRatioTarget(double lossRatioTarget) {
		this.lossRatioTarget = lossRatioTarget;
	}

	public Expense(double lossRatioTarget) {
		this.lossRatioTarget = lossRatioTarget;
	}

}