package com.wakandaspace.drools_price_model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Expense implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("lossRatioTarget")
	private double lossRatioTarget;

	@org.kie.api.definition.type.Label("planName")
	private java.lang.String planName;

	public Expense() {
	}

	public java.lang.String getPlanName() {
		return this.planName;
	}

	public void setPlanName(java.lang.String planName) {
		this.planName = planName;
	}

	public double getLossRatioTarget() {
		return this.lossRatioTarget;
	}

	public void setLossRatioTarget(double lossRatioTarget) {
		this.lossRatioTarget = lossRatioTarget;
	}

	public Expense(double lossRatioTarget, java.lang.String planName) {
		this.lossRatioTarget = lossRatioTarget;
		this.planName = planName;
	}

}