package com.wakandaspace.drools_price_model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ExpenseUtil implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ExpenseUtil() {
    }

    public static java.util.List<com.wakandaspace.drools_price_model.Expense> getExpenses = new java.util.ArrayList<com.wakandaspace.drools_price_model.Expanse>() {
		{
			add(new Expense(0.7, "Red Berryl Lite"));
		}
}