package com.wakandaspace.drools_price_model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Expense implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("lossRatioTarget")
	private double lossRatioTarget;

	@org.kie.api.definition.type.Label(value = "plan")
	private java.lang.String plan;

	public Expense() {
	}

	public double getLossRatioTarget() {
		return this.lossRatioTarget;
	}

	public void setLossRatioTarget(double lossRatioTarget) {
		this.lossRatioTarget = lossRatioTarget;
	}

	public java.lang.String getPlan() {
		return this.plan;
	}

	public void setPlan(java.lang.String plan) {
		this.plan = plan;
	}

	public Expense(double lossRatioTarget, java.lang.String plan) {
		this.lossRatioTarget = lossRatioTarget;
		this.plan = plan;
	}

}