package com.wakandaspace.drools_price_model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LimitFactorUtil implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public LimitFactorUtil() {
	}

	public static java.util.List<com.wakandaspace.drools_price_model.LimitFactor> getLimitFactorsList = new java.util.ArrayList<com.wakandaspace.drools_price_model.LimitFactor>() {
		{
			add(new LimitFactor(800000.0, 0.7981, 0.9701, 0.78172));
		}
	};
	/**
	 * Fonction qui prend en entrée une limite Retourne un objet LimitFactors
	 */
	public static com.wakandaspace.drools_price_model.LimitFactor getFactorsPerLimit(
			double limit) {
		for (LimitFactor limitFactor : getLimitFactorsList) {
			if (limitFactor.getLimit() == limit) {
				return limitFactor;
			}
		}
	}
}