package com.wakandaspace.drools_price_model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class plan implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("hospitalTier")
	private java.lang.String hospitalTier;
	@org.kie.api.definition.type.Label("benefitLimits")
	private double benefitLimits;

	@org.kie.api.definition.type.Label("preAuthorizationRequired")
	private boolean preAuthorizationRequired;

	public plan() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getHospitalTier() {
		return this.hospitalTier;
	}

	public void setHospitalTier(java.lang.String hospitalTier) {
		this.hospitalTier = hospitalTier;
	}

	public double getBenefitLimits() {
		return this.benefitLimits;
	}

	public void setBenefitLimits(double benefitLimits) {
		this.benefitLimits = benefitLimits;
	}

	public boolean isPreAuthorizationRequired() {
		return this.preAuthorizationRequired;
	}

	public void setPreAuthorizationRequired(boolean preAuthorizationRequired) {
		this.preAuthorizationRequired = preAuthorizationRequired;
	}

	public plan(
			java.lang.String name,
			java.lang.String hospitalTier,
			double benefitLimits,
			boolean preAuthorizationRequired,
			java.util.List<com.wakandaspace.drools_price_model.BenefitUtil> benefitsList) {
		this.name = name;
		this.hospitalTier = hospitalTier;
		this.benefitLimits = benefitLimits;
		this.preAuthorizationRequired = preAuthorizationRequired;
		this.benefitsList = benefitsList;
	}

	public plan(java.lang.String name, java.lang.String hospitalTier,
			double benefitLimits, boolean preAuthorizationRequired) {
		this.name = name;
		this.hospitalTier = hospitalTier;
		this.benefitLimits = benefitLimits;
		this.preAuthorizationRequired = preAuthorizationRequired;
	}

}