package com.wakandaspace.drools_price_model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class planUtil implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public planUtil() {
	}
	public static java.util.List<com.wakandaspace.drools_price_model.plan> getRedBerylPlan = new java.util.ArrayList<com.wakandaspace.drools_price_model.plan>() {
		{
			add(new plan("Red Berryl Lite", "Tiers 4", 800000, true,
					BenefitCategoryUtil.getBenefitCategories));
		}
	};

}